### ISSUE TITLE
Do Agenda Feature

### ISSUE THREAD

**Issue by ecoknows** [KUBO-TEAM/KUBO#13]
You can follow this kind of layout
![image](https://user-images.githubusercontent.com/66323903/147809497-171b6e33-8a2b-4970-a462-4cde0d8e33a1.png)

**Comment by serix123** [comment]
Agenda Feature

https://user-images.githubusercontent.com/68373388/149285622-52a458fa-4f1f-4c94-9c44-bed25d3dfad8.mp4

**Comment by serix123** [comment]
https://user-images.githubusercontent.com/68373388/149285757-416a2d1e-67f4-46a5-aa3f-fd0182d2de98.mp4

https://user-images.githubusercontent.com/68373388/149285910-bf35575f-c219-48df-b6d8-4c2fec21100c.mp4
